server:
  port: 8999
logging:
  level:
    root: info
    org.devil.proxy: debug
    org.springframework.boot: debug
    org.springframework.cloud: debug
spring:
  application:
    name: feign-autoproxy-example
management:
  endpoints:
    web:
      exposure:
        include: '*'
